name: Docs Preview

on:
  push:
    branches:
      - test-pages
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          pip3 install sphinx sphinx_rtd_theme

      - name: Sphinx build and TartanGround copy
        run: |
          sphinx-build docs docs/_build/html
          mkdir -p docs/_build/html/tartanground
          cp -r docs/tartanground/* docs/_build/html/tartanground/
          echo "tartanair.org" > docs/_build/html/CNAME

      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages-preview
          force_orphan: true
